name: CI Pipeline de Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run unit tests
      run: python -m unittest discover -s tests -p "*.py"

    - name: Run SAST with Bandit
      run: |
        pip install bandit jq
        bandit -r . -f json -o bandit_report.json || true
        if jq '.results[] | select(.issue_severity == "HIGH" or .issue_severity == "CRITICAL")' bandit_report.json | grep -q .; then
          echo "Vulnérabilités critiques détectées ! Pipeline échoue."
          exit 1
        fi

    - name: Setup Snyk
      uses: snyk/actions/setup@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        snyk-version: 'latest'

    - name: Run SCA with Snyk
      run: snyk test --severity-threshold=high --fail-on=upgradable
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Deploy ephemeral environment
      run: |
        docker build -t mon-app .
        docker run -d -p 8000:8000 --name app mon-app
        # Vérifier que le serveur est prêt
        timeout 60 bash -c "until curl -s http://localhost:8000; do sleep 1; done" || echo "Server failed to start, check logs"
        docker logs app

    - name: Run DAST with OWASP ZAP
      run: |
        # Pull image officielle ZAP
        docker pull owasp/zap2docker-stable
        # Lancer le scan basique
        docker run --network host owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8000 \
            -r zap_report.html \
            -l FAIL
        # Stopper l'app
        docker stop app
